import {histories} from './history.js';
import {playSwing,setSound} from './audio.js';
const $=s=>document.querySelector(s),stage=$('#stage'),dialog=$('#detail');let active=0,selectedInfo=0,ready=false,sound=true,trigger=()=>{},resize=()=>{};
document.querySelectorAll('[data-info]').forEach(b=>b.addEventListener('click',()=>{selectedInfo=+b.dataset.info;const h=histories[selectedInfo];$('#detail-title').textContent=h.name;$('#detail-kicker').textContent=h.kicker;$('#detail-sub').textContent=h.sub;$('#detail-body').innerHTML=h.body;dialog.showModal()}));
$('#close').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
$('#dialog-swing').onclick=()=>{dialog.close();trigger(selectedInfo)};
$('#sound').onclick=()=>{sound=!sound;setSound(sound);$('#sound').setAttribute('aria-pressed',String(sound));$('#sound span').textContent=sound?'Suara aktif':'Suara mati'};
document.querySelectorAll('[data-swing]').forEach(b=>b.onclick=()=>trigger(+b.dataset.swing));
document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>{active=+b.dataset.select;document.querySelectorAll('[data-select]').forEach(x=>x.setAttribute('aria-pressed',String(+x.dataset.select===active)));document.querySelectorAll('.card').forEach(x=>x.classList.toggle('active',+x.dataset.index===active));resize()});
try{
 const T=await import('three');const {makeSword}=await import('./models.js');
 let renderer=new T.WebGPURenderer({alpha:true,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.setClearColor(0,0);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;await renderer.init();stage.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Pedang 3D. Gunakan tombol Ayunkan untuk akses keyboard.');
 const envCanvas=document.createElement('canvas');envCanvas.width=1024;envCanvas.height=512;const ctx=envCanvas.getContext('2d');ctx.fillStyle='#343c48';ctx.fillRect(0,0,1024,512);for(const [x,y,w,h,color] of [[50,20,240,330,'#fff4dc'],[560,40,160,300,'#c4e2ff'],[850,120,130,240,'#ffffff']]){ctx.fillStyle=color;ctx.fillRect(x,y,w,h)}const env=new T.CanvasTexture(envCanvas);env.mapping=T.EquirectangularReflectionMapping;env.colorSpace=T.SRGBColorSpace;
 const items=[0,1,2].map(i=>{const scene=new T.Scene();scene.environment=env;scene.add(new T.HemisphereLight(0xdfeeff,0x171a24,2));const light=new T.DirectionalLight(0xffe5be,4);light.position.set(-3,5,5);scene.add(light);const rim=new T.DirectionalLight(i===2?0x23eaff:0xb7d7ff,3);rim.position.set(3,2,-3);scene.add(rim);const model=makeSword(i);scene.add(model.root);const camera=new T.PerspectiveCamera(38,1,.1,40);camera.position.set(0,1.2,7.4);camera.lookAt(0,1,0);return{...model,scene,camera,rot:model.root.rotation.clone(),turn:model.root.rotation.y,tilt:.03,start:-100,duration:[.8,1.08,.68][i],busy:false}});
 // Fill the dedicated model row. Viewport Y=0 works identically on both backends.
 for(const o of items){const fill=new T.DirectionalLight(0xe2efff,3);fill.position.set(0,1,6);o.scene.add(fill)}
 let width=1,height=1,mobile=false;resize=()=>{width=Math.max(1,stage.clientWidth);height=Math.max(1,stage.clientHeight);mobile=window.innerWidth<=700;renderer.setSize(width,height);const w=mobile?width:width/3;for(const o of items){o.camera.aspect=w/height;o.camera.position.z=Math.max(7.4,4/o.camera.aspect);o.camera.updateProjectionMatrix()}};new ResizeObserver(resize).observe(stage);resize();
 const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;trigger=i=>{if(!ready||items[i].busy)return;const o=items[i];o.start=performance.now()/1000;o.busy=true;playSwing(i);$('#hint').textContent=histories[i].name+' — '+['ringan & tangkas','berat & beresonansi','cepat & elektrik'][i];};
 const ray=new T.Raycaster(),p=new T.Vector2();let drag=null;
 renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;const r=renderer.domElement.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,i=mobile?active:Math.max(0,Math.min(2,Math.floor(x/(width/3))));if(y<0||y>height)return;const w=mobile?width:width/3,left=mobile?0:i*w;p.set((x-left)/w*2-1,1-y/height*2);ray.setFromCamera(p,items[i].camera);if(ray.intersectObject(items[i].root,true).length){trigger(i)}else{drag={i,x:e.clientX,y:e.clientY};renderer.domElement.setPointerCapture(e.pointerId)}});
 renderer.domElement.addEventListener('pointermove',e=>{if(!drag)return;const o=items[drag.i];o.turn+=(e.clientX-drag.x)*.009;o.tilt=T.MathUtils.clamp(o.tilt+(e.clientY-drag.y)*.004,-.4,.4);drag.x=e.clientX;drag.y=e.clientY});const end=()=>drag=null;['pointerup','pointercancel','lostpointercapture'].forEach(n=>renderer.domElement.addEventListener(n,end));window.addEventListener('blur',end);
 let last=performance.now()/1000;renderer.setAnimationLoop(()=>{const now=performance.now()/1000,dt=Math.min(now-last,.04);last=now;renderer.setScissorTest(false);renderer.clear();renderer.setScissorTest(true);items.forEach((o,i)=>{if(mobile&&i!==active)return;const t=(now-o.start)/o.duration;let swing=0,side=0;if(t>=0&&t<1){if(t<.18){swing=-.23*Math.sin(t/.18*Math.PI/2)}else if(t<.5){const u=(t-.18)/.32; swing=-.23+1.7*(1-Math.pow(1-u,3));side=-.32*Math.sin(u*Math.PI/2)}else{const u=(t-.5)/.5;swing=1.47*Math.exp(-6*u)*Math.cos(u*9);side=-.32*(1-u)} }else o.busy=false;
 o.pivot.rotation.x=reduced?swing*.12:swing;o.pivot.rotation.z=reduced?0:side;o.root.rotation.y+=(o.turn-o.root.rotation.y)*Math.min(1,dt*12);o.root.rotation.x=o.tilt;o.root.position.y=reduced?0:Math.sin(now*.8+i)*.018;o.energy.emissiveIntensity=2.4+(reduced?0:Math.sin(now*2)*.4);o.trail.visible=i===2&&t>.25&&t<.65&&!reduced;o.trail.children.forEach((m,j)=>m.material.opacity=(1-j/6)*.24*Math.max(0,Math.sin((t-.25)/.4*Math.PI)));
 const w=mobile?width:width/3,x=mobile?0:i*w;renderer.setViewport(x,0,w,height);renderer.setScissor(x,0,w,height);renderer.render(o.scene,o.camera)});});
 ready=true;$('#loading').remove();document.querySelectorAll('[data-swing]').forEach(b=>b.disabled=false);
}catch(error){console.error(error);$('#loading').textContent='Tampilan 3D tidak dapat dimuat. Gunakan browser dengan WebGPU atau WebGL 2, lalu muat ulang. Informasi pedang tetap dapat dibuka.';$('#dialog-swing').disabled=true;}
